apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fineract-server
  name: fineract-server-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
